id: I550A47C8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:48:15+00:00'
last_modified: '2022-06-09T07:43:35.762024+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29498
  title: ངག་རྩོམ་ནོར་བུའི་གཏེར་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    F61A:
      image_group_id: I1KG12366
      title: Volume 1 of ngag rtsom nor bu'i gter 'bum/
      total_pages: 420
      order: 1
      base_file: F61A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
