id: P007936
initial_creation_type: ocr
source_metadata:
  id: bdr:W29498
  title: ངག་རྩོམ་ནོར་བུའི་གཏེར་འབུམ།
  author: ''
  volumes:
    cd671b5b64d44afeb0cffa48383f29e8:
      image_group_id: I1KG12366
      title: ''
      volume_number: 1
      total_pages: 420
ebook_metadata:
  title: ངག་རྩོམ་ནོར་བུའི་གཏེར་འབུམ།
  author: ''
  sku: P007936
  cover: cover.jpg
  layers:
  - pagination
